DSRS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from student import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    url(r'^$', views.index_view, name='index'),
    url(r'^about/', views.AboutView.as_view(), name='about'),
    url(r'^contactus/', views.ContactUsView.as_view(), name='contactus'),
    url(r'^depts/', views.DeptsView.as_view(), name='depts'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^home/$', views.home, name='home'),


]

student/urls.py
from django.conf.urls import url
from student import views

# App Name Tag
app_name = 'student'

urlpatterns = [
    url(r'^student_home/', views.StudentView.as_view(), name='stud_home'),
    url(r'^department_home/', views.DeptView.as_view(), name='dep_home'),
    url(r'^office_home/', views.OfficeView.as_view(), name='off_home'),
    url(r'^hod_home/', views.HodView.as_view(), name='hod_home'),
    url(r'^requisition_apply/', views.form_submit, name='form_submit'),
    url(r'^accept_reject/', views.accept_reject, name='accept_reject'),

]

student/models.py
from django.db import models

# Create your models here.


class Faculty(models.Model):
    name = models.CharField(max_length=50)
    facid = models.CharField(max_length=6, primary_key=True)
    dept = models.CharField(max_length=4)
    phone = models.PositiveIntegerField()
    email = models.EmailField(max_length=256, unique=True)


class Student(models.Model):
    name = models.CharField(max_length=50)
    usn = models.CharField(max_length=10, primary_key=True)
    dept = models.CharField(max_length=4)
    facid = models.ForeignKey(Faculty, related_name='faculties', on_delete='cascade')
    phone = models.PositiveIntegerField()
    email = models.EmailField(max_length=256, unique=True)


class Office(models.Model):
    name = models.CharField(max_length=50)
    office_id = models.CharField(max_length=10, primary_key=True)
    office_section = models.CharField(max_length=50)
    phone = models.PositiveIntegerField()
    email = models.EmailField(max_length=256, unique=True)


class Requisitions(models.Model):
    name = models.CharField(max_length=50)
    usn = models.ForeignKey(Student, on_delete='cascade')
    facid = models.ForeignKey(Faculty, on_delete='cascade')
    reqid = models.CharField(max_length=7, primary_key=True)
    phone = models.PositiveIntegerField()
    email = models.EmailField(max_length=256)
    date = models.DateTimeField()
    subject = models.TextField(max_length=50)
    office_section = models.TextField(max_length=30)
    issue = models.TextField(max_length=30)
    reason = models.TextField(max_length=100)
    proc_appr = models.PositiveIntegerField(default=0)
    hod_appr = models.PositiveIntegerField(default=0)
    office_appr = models.PositiveIntegerField(default=0)

student/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from student.models import *
from django.views.generic import TemplateView
import datetime, random
# Create your views here.


def index_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        tab_selected = request.POST.get('tab_selected')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                request.session['username'] = username
                request.session['tab_selected'] = tab_selected
                if tab_selected == 'student_tab':
                    return HttpResponseRedirect(reverse('student:stud_home'))
                elif tab_selected == 'dept_tab':
                    if username[:3] == 'hod':
                        return HttpResponseRedirect(reverse('student:hod_home'))
                    else:
                        return HttpResponseRedirect(reverse('student:dep_home'))
                elif tab_selected == 'office_tab':
                    return HttpResponseRedirect(reverse('student:off_home'))
            else:
                user_login = 'inactive'
                return render(request, 'student/index.html', context={'login': user_login})
        else:
            user_login = 'invalid'
            return render(request, 'student/index.html', context={'login': user_login})
    else:
        return render(request, 'student/index.html', context={})


@login_required
def user_logout(request):
    logout(request)
    for sesskey in request.session.keys():
        del request.session[sesskey]
    return HttpResponseRedirect(reverse('index'))


@login_required()
def home(request):
    tab_selected = request.session['tab_selected']
    username = request.session['username']
    if tab_selected == 'student_tab':
        return HttpResponseRedirect(reverse('student:stud_home'))
    elif tab_selected == 'dept_tab':
        if username[:3] == 'hod':
            return HttpResponseRedirect(reverse('student:hod_home'))
        else:
            return HttpResponseRedirect(reverse('student:dep_home'))
    elif tab_selected == 'office_tab':
        return HttpResponseRedirect(reverse('student:off_home'))


class AboutView(TemplateView):
    template_name = 'student/about.html'


class DeptsView(TemplateView):
    template_name = 'student/depts_navbar.html'


class ContactUsView(TemplateView):
    template_name = 'student/contact_us.html'


class StudentView(TemplateView):
    template_name = 'student/student_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.session['username']
        student = Student.objects.get(email=username)
        requisitions = Requisitions.objects.filter(usn=student.usn)
        context['student_data'] = student
        context['req_done'] = requisitions
        return context


@login_required()
def form_submit(request):
    username = request.session['username']
    student = Student.objects.get(email=username)
    if request.method == 'POST':

        dates = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        issu = request.POST.get('issue')
        issu = issu[:2]
        off_sec = request.POST.get('office_section')
        off_sec = off_sec[:2]
        num = random.randint(0, 100)
        reqid = issu + off_sec + str(num)
        try:
            db = Requisitions.objects.create(name=student.name,
                                             usn=student,
                                             facid=student.facid,
                                             reqid=reqid,
                                             phone=student.phone,
                                             email=student.email,
                                             date=dates,
                                             subject=request.POST.get('subject'),
                                             office_section=request.POST.get('office_section'),
                                             issue=request.POST.get('issue'),
                                             reason=request.POST.get('reason'),
                                            )
            db.save()
            db_save_status = True
        except:
            db_save_status = False
        return render(request, 'student/student_home.html', {'db_handle': db_save_status,
                                                             'student_data': student,
                                                             'req_done': Requisitions.objects.filter(usn=student.usn)})
    else:
        return render(request, 'student/student_home.html', {})


class DeptView(TemplateView):
    template_name = 'student/department_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.session['username']
        faculty = Faculty.objects.get(email=username)
        requisitions = Requisitions.objects.filter(facid=faculty.facid, proc_appr=0)
        requisitions_approved = Requisitions.objects.exclude(facid=faculty.facid, proc_appr=0)
        context['faculty_data'] = faculty
        context['req_data'] = requisitions
        context['req_done'] = requisitions_approved
        return context


class OfficeView(TemplateView):
    template_name = 'student/office_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.session['username']
        office = Office.objects.get(email=username)
        requisitions = Requisitions.objects.filter(proc_appr=1, hod_appr=1, office_appr=0)
        requisitions_approved = Requisitions.objects.filter(proc_appr=1, hod_appr=1).exclude(office_appr=0)
        context['office_data'] = office
        context['req_data'] = requisitions
        context['req_done'] = requisitions_approved
        return context


class HodView(TemplateView):
    template_name = 'student/hod_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.session['username']
        faculty = Faculty.objects.get(email=username)
        requisitions = Requisitions.objects.filter(proc_appr=1, hod_appr=0)
        requisitions_approved = Requisitions.objects.exclude(facid=faculty.facid, proc_appr=1, hod_appr=0)
        context['faculty_data'] = faculty
        context['req_data'] = requisitions
        context['req_done'] = requisitions_approved
        return context


@login_required()
def accept_reject(request):
    username = request.session['username']
    tab_selected = request.session['tab_selected']
    if tab_selected == 'office_tab':
        office = Office.objects.get(email=username)
    if tab_selected == 'dept_tab':
        faculty = Faculty.objects.get(email=username)
    req_id = request.POST.get('req_id')
    btn_appr = request.POST.get('appr_btn')
    rej_btn = request.POST.get('rej_btn')
    if btn_appr == '1' and tab_selected == 'dept_tab' and username[:3] != 'hod':
        reqsns_table = Requisitions.objects.get(reqid=req_id)
        reqsns_table.proc_appr = 1
        reqsns_table.save()
        return render(request, 'student/department_home.html', {'faculty_data': faculty,
                                                                'req_data': Requisitions.objects.filter(facid=faculty.facid, proc_appr=0),
                                                                'req_done': Requisitions.objects.exclude(facid=faculty.facid, proc_appr=0)})

    if btn_appr == '1' and tab_selected == 'dept_tab' and username[:3] == 'hod':
        reqsns_table = Requisitions.objects.get(reqid=req_id)
        reqsns_table.hod_appr = 1
        reqsns_table.save()
        return render(request, 'student/hod_home.html', {'faculty_data': faculty,
                                                         'req_data': Requisitions.objects.filter(proc_appr=1, hod_appr=0),
                                                         'req_done': Requisitions.objects.exclude(facid=faculty.facid, proc_appr=1, hod_appr=0)})

    if btn_appr == '1' and tab_selected == 'office_tab':
        reqsns_table = Requisitions.objects.get(reqid=req_id)
        reqsns_table.office_appr = 1
        reqsns_table.save()
        return render(request, 'student/office_home.html', {'office_data': office,
                                                            'req_data': Requisitions.objects.filter(proc_appr=1, hod_appr=1, office_appr=0),
                                                            'req_done': Requisitions.objects.filter(proc_appr=1, hod_appr=1).exclude(office_appr=0)})

    if rej_btn == '1' and tab_selected == 'dept_tab' and username[:3] != 'hod':
        reqsns_table = Requisitions.objects.get(reqid=req_id)
        reqsns_table.proc_appr = 2
        reqsns_table.save()
        return render(request, 'student/department_home.html', {'faculty_data': faculty,
                                                                'req_data': Requisitions.objects.filter(facid=faculty.facid, proc_appr=0),
                                                                'req_done': Requisitions.objects.exclude(facid=faculty.facid, proc_appr=0)})

    if rej_btn == '1' and tab_selected == 'dept_tab' and username[:3] == 'hod':
        reqsns_table = Requisitions.objects.get(reqid=req_id)
        reqsns_table.hod_appr = 2
        reqsns_table.save()
        return render(request, 'student/hod_home.html', {'faculty_data': faculty,
                                                         'req_data': Requisitions.objects.filter(proc_appr=1, hod_appr=0),

templates/student/department_home.html
{% extends 'student/base_others.html' %}
{% block body_block %}

    <div class="card" style="width: 100%; margin:auto;">
        <div class="card-body">
            <span style="margin-left: 20px; margin-top: 20px;">Welcome, </span>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".bd-example-modal-lg1" style="float: right; margin-right: 20px; margin-top:30px">
                Previous Forms
            </button><br>
            <br><span style="margin-left: 50px;">Name : {{ faculty_data.name }} </span> <!-- insert from db -->  <span style="margin-right: 250px; float:right;">Dept : {{ faculty_data.dept.upper }}</span><!-- insert from db --><br>
            <br><br><span style="margin-left: 50px;">FacID : {{ faculty_data.facid }}</span><!-- insert from db -->
        </div>
    </div>
    <br><br>
    <!-- card and tabs for student details applications -->

    <!-- Dynamic Cards. If exists: Select the rows of data from db. count the no of rows and generate so many cards by placing in loop. -->
    {% if req_data %}
        {% for reqsns in req_data %}
        <br>
        <div class="card" style="width: 100%; margin: auto;">
            <div class="card-header">
                <h4 class="card-title">ISSUE: {{ reqsns.issue}}</h4>
            </div>
            <div class="card-body">
                <form action="{% url 'student:accept_reject' %}" method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="subject" style="color:black"><b>SUBJECT: {{ reqsns.subject }}</b></label>
                    </div>
                    <div class="form-group" style="float: right; margin-right: 250px;">
                        <label for="usn" style="color:black"><b>USN: {{ reqsns.usn.usn }}</b></label>
                    </div>
                    <div class="form-group">
                        <label for="name" style="color:black"><b>NAME: {{ reqsns.name }}</b></label>
                    </div>

                    <div class="form-group">
                        <label for="reason" style="color:black"><b>REASON: {{ reqsns.reason }}</b></label>
                    </div>
                    <div class="form-group">
                        <input type="hidden" value="{{ reqsns.reqid }}" name="req_id">
                    </div>
                    <div class="text-center">
                        <button type="submit" name='appr_btn' value="1" class="btn btn-info">APPROVE</button>
                        <button type="submit" name="rej_btn" value="1" style="margin-left: 20px;" class="btn btn-danger">REJECT</button>
                    </div>
                </form>
            </div>
        </div>
    <br><br>

    {% endfor %}

    {% else %}

        <p class="mb-1" ><h4 style="text-align: center"> No Requisitions </h4></p>

    {% endif %}

    <!-- end of card of student-->
    <!-- Modal for view applications-->
    <div class="modal fade bd-example-modal-lg1" id="viewapplied" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" style="color: black;">Previous Requisitions::</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" style="color:black;">
                    <!-- card for content -->
                    {% if req_done %}
                    {% for reqs in req_done %}
                    <br>
                    <div class="card" style="width: 100%; margin: auto;">
                        <div class="card-header">
                            <h4 class="card-title">ISSUE: {{ reqs.issue }}</h4>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <label for="subject" style="color:black"><b>SUBJECT : {{ reqs.subject }}</b></label>
                                </div>
                                <div class="form-group" style="float: right; margin-right: 250px;">
                                    <label for="usn" style="color:black"><b>USN : {{ reqs.usn.usn }}</b></label>
                                </div>
                                <div class="form-group">
                                    <label for="name" style="color:black"><b>NAME:{{ reqs.name }}</b></label>
                                </div>
                                <div class="form-group" style="float: right; margin-right: 250px;">
                                    <label for="status" style="color:black"><b>STATUS : {% if reqs.proc_appr == 1 %}Approved{% elif reqs.proc_appr == 2 %}Rejected{% endif %}</b></label>
                                </div>
                                <div class="form-group">
                                    <label for="reason" style="color:black"><b>REASON: {{ reqs.reason }}</b></label>
                                </div>

                            </form>
                        </div>
                    </div>
                        <br>
                    {% endfor %}
                {% else %}

                    <p class="mb-1"> None</p>

                {% endif %}

                    <!-- end of cards-->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

templates/student/hod_home.html
{% extends 'student/base_others.html' %}
{% block body_block %}

    <div class="card" style="width: 100%; margin:auto;">
        <div class="card-body">
            <span style="margin-left: 20px; margin-top: 20px;">Welcome, </span>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".bd-example-modal-lg1" style="float: right; margin-right: 20px; margin-top:30px">
                Previous Forms
            </button><br>
            <br><span style="margin-left: 50px;">Name : {{ faculty_data.name }} </span> <!-- insert from db -->  <span style="margin-right: 250px; float:right;">Dept : {{ faculty_data.dept }} HOD</span><!-- insert from db --><br>
            <br><br><span style="margin-left: 50px;">FacID : {{ faculty_data.facid }}</span><!-- insert from db -->
        </div>
    </div>
    <br><br>
    <!-- card and tabs for student details applications -->

    <!-- Dynamic Cards. If exists: Select the rows of data from db. count the no of rows and generate so many cards by placing in loop. -->
    {% if req_data %}
        {% for reqsns in req_data %}
               <br>
            <div class="card" style="width: 100%; margin: auto;">
                <div class="card-header">
                    <h4 class="card-title">ISSUE: {{ reqsns.issue}}</h4>
                </div>
                <div class="card-body">
                    <form action="{% url 'student:accept_reject' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="subject" style="color:black"><b>SUBJECT: {{ reqsns.subject }}</b></label>
                        </div>
                        <div class="form-group" style="float: right; margin-right: 250px;">
                            <label for="usn" style="color:black"><b>USN: {{ reqsns.usn.usn }}</b></label>
                        </div>
                        <div class="form-group">
                            <label for="name" style="color:black"><b>NAME: {{ reqsns.name }}</b></label>
                        </div>

                        <div class="form-group">
                            <label for="reason" style="color:black"><b>REASON: {{ reqsns.reason }}</b></label>
                        </div>
                        <div class="form-group">
                            <input type="hidden" value="{{ reqsns.reqid }}" name="req_id">
                        </div>
                        <div class="text-center">
                            <button type="submit" name='appr_btn' value="1" class="btn btn-info">APPROVE</button>
                            <button type="submit" name="rej_btn" value="1" style="margin-left: 20px;" class="btn btn-danger">REJECT</button>
                        </div>
                    </form>
                </div>
            </div>
            <br><br>

        {% endfor %}

    {% else %}

        <p class="mb-1"> No Requisitions</p>

    {% endif %}

    <!-- end of card of student-->
    <!-- Modal for view applications-->
    <div class="modal fade bd-example-modal-lg1" id="viewapplied" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" style="color: black;">Previous Requisitions::</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" style="color:black;">
                    <!-- card for content -->
                    {% if req_done %}
                        {% for reqs in req_done %}
                            <br>
                            <div class="card" style="width: 100%; margin: auto;">
                                <div class="card-header">
                                    <h4 class="card-title">ISSUE: {{ reqs.issue }}</h4>
                                </div>
                                <div class="card-body">
                                    <form>
                                        <div class="form-group">
                                            <label for="subject" style="color:black"><b>SUBJECT : {{ reqs.subject }}</b></label>
                                        </div>
                                        <div class="form-group" style="float: right; margin-right: 250px;">
                                            <label for="usn" style="color:black"><b>USN : {{ reqs.usn.usn }}</b></label>
                                        </div>
                                        <div class="form-group">
                                            <label for="name" style="color:black"><b>NAME:{{ reqs.name }}</b></label>
                                        </div>
                                        <div class="form-group" style="float: right; margin-right: 250px;">
                                            <label for="status" style="color:black"><b>STATUS : {% if reqs.proc_appr == 1 and reqs.hod_appr == 1 %}Approved{% elif reqs.proc_appr == 1 and reqs.hod_appr == 2 %}Rejected{% endif %}</b></label>
                                        </div>
                                        <div class="form-group">
                                            <label for="reason" style="color:black"><b>REASON: {{ reqs.reason }}</b></label>
                                        </div>

                                    </form>
                                </div>
                            </div>
                            <br><br>
                        {% endfor %}
                    {% else %}

                        <p class="mb-1"> None</p>

                    {% endif %}

                    <!-- end of cards-->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

templates/student/office_home.html
{% extends 'student/base_others.html' %}
{% block body_block %}

    <div class="card" style="width: 100%; margin:auto;">
        <div class="card-body">
            <span style="margin-left: 20px; margin-top: 20px;">Welcome, </span><br>
            <br><span style="margin-left: 50px;">Name : {{ office_data.name }} </span> <!-- insert from db -->  <span style="margin-right: 250px; float:right;">Section : {{ office_data.office_section }}</span><!-- insert from db --><br>
            <br><br><span style="margin-left: 50px;">OfficeId : {{ office_data.office_id }}</span><!-- insert from db -->
        </div>
    </div>
    <br><br>
    <!-- card and tabs for student details applications -->

    <!-- Dynamic Cards. If exists: Select the rows of data from db. count the no of rows and generate so many cards by placing in loop. -->
    <div class="card card-nav-tabs card-plain" style="width: 80%; margin: auto;">
        <div class="card-header card-header-danger">
    <div class="nav-tabs-navigation">
        <div class="nav-tabs-wrapper">
            <ul class="nav nav-tabs" data-tabs="tabs">
                <li class="nav-item">
                    <a class="nav-link active" href="#newapply" data-toggle="tab">Forms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#applied" data-toggle="tab">View Cleared Forms</a>
                </li>
            </ul>
        </div>
    </div>
    </div>
    <div class="card-body ">
        <div class="tab-content text-center">
            <div class="tab-pane active" id="newapply">
            <br>
    {% if req_data %}
        {% for reqsns in req_data %}

            <div class="card" style="width: 100%; margin: auto;">
                <div class="card-header">
                    <h4 class="card-title">ISSUE: {{ reqsns.issue}}</h4>
                </div>
                <div class="card-body">
                    <form action="{% url 'student:accept_reject' %}" method="post">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="subject" style="color:black"><b>SUBJECT: {{ reqsns.subject }}</b></label>
                        </div>
                        <div class="form-group" style="float: right; margin-right: 250px;">
                            <label for="usn" style="color:black"><b>USN: {{ reqsns.usn.usn }}</b></label>
                        </div>
                        <div class="form-group">
                            <label for="name" style="color:black"><b>NAME: {{ reqsns.name }}</b></label>
                        </div>

                        <div class="form-group">
                            <label for="reason" style="color:black"><b>REASON: {{ reqsns.reason }}</b></label>
                        </div>
                        <div class="form-group">
                            <input type="hidden" value="{{ reqsns.reqid }}" name="req_id">
                        </div>
                        <div class="text-center">
                            <button type="submit" name='appr_btn' value="1" class="btn btn-info">APPROVE</button>
                            <button type="submit" name="rej_btn" value="1" style="margin-left: 20px;" class="btn btn-danger">REJECT</button>
                        </div>
                    </form>
                </div>
            </div>
            <br><br>

        {% endfor %}

    {% else %}

        <p class="mb-1"> No Requisitions</p>

    {% endif %}

            </div>
            <div class="tab-pane" id="applied">

                {% if req_done %}
                    {% for reqs in req_done %}
                        <br>
                        <div class="card" style="width: 100%; margin: auto;">
                            <div class="card-header">
                                <h4 class="card-title">ISSUE: {{ reqs.issue }}</h4>
                            </div>
                            <div class="card-body">
                                <form>
                                    <div class="form-group">
                                        <label for="subject" style="color:black"><b>SUBJECT : {{ reqs.subject }}</b></label>
                                    </div>
                                    <div class="form-group" style="float: right; margin-right: 250px;">
                                        <label for="usn" style="color:black"><b>USN : {{ reqs.usn.usn }}</b></label>
                                    </div>
                                    <div class="form-group">
                                        <label for="name" style="color:black"><b>NAME:{{ reqs.name }}</b></label>
                                    </div>

                                    <div class="form-group" style="float: left; margin-left: 100px">
                                        <label for="reason" style="color:black"><b>REASON: {{ reqs.reason }}</b></label>
                                    </div>
                                    <div class="form-group" style="float: right; margin-right: 250px;">
                                        <label for="status" style="color:black"><b>STATUS : {% if reqs.office_appr == 1 %}Approved{% elif reqs.office_appr == 2 %}Rejected{% endif %}</b></label>
                                    </div>


                                </form>
                            </div>
                        </div>
                        <br><br>
                    {% endfor %}
                {% else %}

                    <p class="mb-1"> None</p>

                {% endif %}

            </div>
        </div>
    </div>
    </div>

    <!-- end of card of student-->





{% endblock %}